name: Update Submodules

on:
  workflow_dispatch:

# jobs:
#   update-submodules:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
#         with:
#           submodules: true

#       - name: Update submodules
#         run: git submodule update --remote --merge

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0 

      - name: Submodule update
        run: |
          git submodule init
          git submodule update --remote --merge

      - name: Commit submodule updates if changes exist
        run: |
          # If changes were detected, commit the updated submodules
          if [[ $(git diff --exit-code) ]]; then
            git add .
            git commit -m "Update submodules"
            git push
          else
            echo "No submodule updates detected, skipping commit."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
